### ISSUE TITLE
Does not work on Debian Stable (python 3.7.3)

### ISSUE THREAD

**Issue by jepler** [adafruit/cascadetoml#1]
I encountered the following error:
```
python3 ../cascadetoml/cascadetoml.py cascade filter 'sku="GD25Q64C"'
Traceback (most recent call last):
  File "../cascadetoml/cascadetoml.py", line 393, in <module>
    app()
  File "/home/jepler/.local/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/jepler/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jepler/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jepler/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jepler/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jepler/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jepler/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jepler/.local/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "../cascadetoml/cascadetoml.py", line 184, in filter
    output_doc = _cascade(list(root.glob("*/**/*.toml")))
  File "../cascadetoml/cascadetoml.py", line 109, in _cascade
    if not parent.is_relative_to(root.parent):
AttributeError: 'PosixPath' object has no attribute 'is_relative_to'
```
`is_relative_to` is new in Python 3.9. https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.is_relative_to

**Comment by tannewt** [comment]
Fixed in 613b71e95c779ded24ac6751a2a22994b6ca92c9
