### ISSUE TITLE
Does not install using `flit install` on Debian Stable (Python 3.7.3)

### ISSUE THREAD

**Issue by jepler** [adafruit/cascadetoml#2]
When I try to install (with `flit install`) I get an error:
```
$ flit install
Extras to install for deps 'all': {'.none'}                                                                         I-flit.install
Processing /home/jepler/src/cascadetoml
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: typer in /home/jepler/.local/lib/python3.7/site-packages (from cascadetoml==0.2.0) (0.3.2)
Requirement already satisfied: tabulate in /home/jepler/.local/lib/python3.7/site-packages (from cascadetoml==0.2.0) (0.8.6)
Requirement already satisfied: tomlkit in /home/jepler/.local/lib/python3.7/site-packages (from cascadetoml==0.2.0) (0.7.0)
Requirement already satisfied: parse in /home/jepler/.local/lib/python3.7/site-packages (from cascadetoml==0.2.0) (1.19.0)
Requirement already satisfied: click<7.2.0,>=7.1.1 in /home/jepler/.local/lib/python3.7/site-packages (from typer->cascadetoml==0.2.0) (7.1.2)
Building wheels for collected packages: cascadetoml
  Building wheel for cascadetoml (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/jepler/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpdhoys63q
       cwd: /tmp/pip-req-build-swc5y1i6
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/home/jepler/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/jepler/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/jepler/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-cww1zsoj/overlay/lib/python3.7/site-packages/flit_core/buildapi.py", line 61, in build_wheel
      info = make_wheel_in(pyproj_toml, Path(wheel_directory))
    File "/tmp/pip-build-env-cww1zsoj/overlay/lib/python3.7/site-packages/flit_core/wheel.py", line 233, in make_wheel_in
      wb.build()
    File "/tmp/pip-build-env-cww1zsoj/overlay/lib/python3.7/site-packages/flit_core/wheel.py", line 221, in build
      self.write_metadata()
    File "/tmp/pip-build-env-cww1zsoj/overlay/lib/python3.7/site-packages/flit_core/wheel.py", line 201, in write_metadata
      self._add_file(path, '%s/%s' % (self.dist_info, osp.basename(path)))
    File "/tmp/pip-build-env-cww1zsoj/overlay/lib/python3.7/site-packages/flit_core/wheel.py", line 152, in _add_file_zf36
      with open(full_path, 'rb') as src, self.wheel_zip.open(zinfo, 'w') as dst:
  IsADirectoryError: [Errno 21] Is a directory: 'LICENSES'
  ----------------------------------------
  ERROR: Failed building wheel for cascadetoml
Failed to build cascadetoml
ERROR: Could not build wheels for cascadetoml which use PEP 517 and cannot be installed directly
Traceback (most recent call last):
  File "/home/jepler/.local/bin/flit", line 8, in <module>
    sys.exit(main())
  File "/home/jepler/.local/lib/python3.7/site-packages/flit/__init__.py", line 172, in main
    pth=args.pth_file).install()
  File "/home/jepler/.local/lib/python3.7/site-packages/flit/install.py", line 415, in install
    self.install_with_pip()
  File "/home/jepler/.local/lib/python3.7/site-packages/flit/install.py", line 353, in install_with_pip
    check_call(cmd, shell=shell)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '.', '--user']' returned non-zero exit status
```
I see there's some attent to exclude LICENSES but it seems not to be effective when using `flit install`.  `flit build` + ` pip install dist/*.whl`  does install, though it encounters a problem due to pre-3.9 Python incompatibility (#1)

**Comment by tannewt** [comment]
Ya, I've seen this too. I'm not sure why it does that.

**Comment by jepler** [comment]
I reported it upstream https://github.com/takluyver/flit/issues/399 so we can see what we learn
